# backend/ingest/dscr_config.py

DSCR_Parameters = [
    "2-1 Buydown",
    "Accessory Dwelling Units",
    "Property - Acreage and Land Value",
    "Age of Loan Documentation",
    "Appraisal Requirements",
    "Assets - Business Assets",
    "Assets - Eligibility, Sourcing & Verification",
    "Assets - Foreign Assets",
    "Assets - Ineligible Sources",
    "Automatic Payment Authorization (ACH)",
    "Borrower Eligibility",
    "Borrowers - Ineligible",
    "Business Purpose Loans",
    "Cash-Out",
    "Cash-Out Refinance Seasoning & Requirements",
    "Collections, Charge-Offs and Judgments",
    "Condo - Warrantable / Established Condos",
    "Condo - Warrantable / Established Condos",
    "Condo - Warrantable / Limited Review",
    "Condo in Need of Critical Repair / Deferred Maintenance",
    "Condo Insurance Requirements",
    "Condos Non-Warrantable",
    "Condo Non-Warrantable",
    "Condotels",
    "Continuity of Obligation / Ownership Seasoning",
    "Credit Report",
    "Credit Rescore",
    "Credit Score Requirements",
    "Credit Score Requirements",
    "Credit/Housing Event Seasoning",
    "Credit/Housing Event Seasoning",
    "Borrower - DACA / ITIN",
    "Declining Markets",
    "Delayed Financing",
    "DSCR Ratio Requirements",
    "Entity Vesting - Signature Requirements",
    "Escrow Holdbacks",
    "Escrow Impounds / HPML / Flood Insurance",
    "Borrower - Experienced Investor",
    "Borrower First Time Investors",
    "Borrower - First-Time Home Buyers",
    "Flip Transactions",
    "Forbearance / Mortgage Modification / Deferment",
    "Gift Funds",
    "Grantor Documentation for Entity Vesting",
    "Gross Rent Requirements",
    "Subordinate Financing - HELOC / Closed End Second Lien",
    "Housing History - Incomplete and Rent Free",
    "Housing History Verification",
    "Housing / Rental History",
    "Housing Payment History Documentation Requirements",
    "Inherited Properties",
    "Interest Credit",
    "Interest-Only",
    "Interest-Only",
    "IPCs",
    "Loan Amounts",
    "Loan Amounts",
    "Loan Purpose",
    "LTV",
    "LTV",
    "Maximum Concentration Exposure (Condo Projects)",
    "Maximum Exposure",
    "Multiple Financed Properties",
    "Borrower - Non-Permanent Resident Alien",
    "Personal Guaranty",
    "Power of Attorney",
    "Prepayment Penalties",
    "Products",
    "Products",
    "Properties Listed for Sale",
    "Property Types - Eligible",
    "Property Types - Ineligible",
    "Rate/Term Refinance",
    "Rate/Term Refinance - Other",
    "Rents Loss Insurance",
    "Reserves",
    "Rural Properties",
    "Short-Term Rentals",
    "State Restrictions",
    "Subordinate Financing - HELOC / Closed End Second Lien",
    "Subordinate Financing - HELOC / Closed End Second Lien",
    "Title Insurance Requirements",
    "Tradelines Requirements",
    "Underwriting Method",
    "Vacant / Unleased Properties",
    "Vesting & Ownership",
    "Permanent Resident Aliens"
]

DSCR_Parameter_Aliases = {
    "Age of Loan Documentation": ["AGE OF DOCUMENT REQUIREMENTS"]
}
